{{- if .Values.leaseRelease.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
metadata:
  name: {{ include "hyrax.fullname" . }}-lease-task
  labels:
    {{- include "hyrax.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.leaseRelease.schedule | default "0 0 * * *" | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
        {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        spec:
          containers:
          - name: lease-release
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command:
            - /bin/sh
            - -c
            - bundle exec rake hyrax:lease:deactivate_expired
          restartPolicy: OnFailure
{{- end }}
