language: ruby
cache: bundler
sudo: false
rvm: 2.3.0

matrix:
  include:
    - rvm: 2.2.4
      env: "BLACKLIGHT_VERSION=6.0.0"
    - rvm: 2.2.4
      env: "BLACKLIGHT_VERSION=5.17.2"

notifications:
  irc: "irc.freenode.org#projecthydra"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
