language: ruby
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3

gemfile:
  - gemfiles/gemfile.rails42
  - gemfiles/gemfile.rails41
  - gemfiles/gemfile.rails40

notifications:
  irc: "irc.freenode.org#projecthydra"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
