apiVersion: v2
name: fcrepo
description: Fedora Commons Repository 4
type: application
version: 0.2.5
appVersion: 4.7
dependencies:
  - name: postgresql
    version: 9.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
