analytics:
  google:
    analytics_id: <%= ENV['GOOGLE_ANALYTICS_ID'] %>
    app_name: <%= ENV.fetch('GOOGLE_OAUTH_APP_NAME', 'nurax-pg') %>
    app_version: <%= ENV.fetch['GOOGLE_OAUTH_APP_VERSION'] %>
    privkey_path: <%= ENV.fetch['GOOGLE_OAUTH_PRIVATE_KEY_PATH'] %>
    privkey_secret: <%= ENV.fetch['GOOGLE_OAUTH_PRIVATE_KEY_SECRET'] %>
    client_email: <%= ENV.fetch['GOOGLE_OAUTH_CLIENT_EMAIL'] %>
  matomo:
    base_url: <%= ENV['MATOMO_BASE_URL'] %>
    site_id: <%= ENV['MATOMO_SITE_ID'] %>
    auth_token: <%= ENV['MATOMO_AUTH_TOKEN'] %>
