---
m3_version: 1.0.beta2
profile:
  date_modified: '2024-06-01'
  responsibility: https://samvera.org
  responsibility_statement: Hyrax Initial Profile
  type:
  version: 1
classes:
  Hyrax::Work:
    display_label: Work
  Hyrax::AdministrativeSet:
    diplay_label: AdministrativeSet
  Hyrax::PcdmCollection:
    display_label: PcdmCollection
  Hyrax::FileSet:
    display_label: FileSet
contexts:
  flexible_context:
    display_label: Flexible Metadata Example
mappings:
  blacklight:
    name: Additional Blacklight Solr Mappings
  metatags:
    name: Metatags
  mods_oai_pmh:
    name: MODS OAI PMH
  qualified_dc_pmh:
    name: Qualified DC OAI PMH
  simple_dc_pmh:
    name: Simple DC OAI PMH
properties:
  title:
    available_on:
      class:
      - Hyrax::AdministrativeSet
      - Hyrax::FileSet
      - Hyrax::PcdmCollection
      - Hyrax::Work
    cardinality:
      minimum: 0
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    definition:
      default: Enter a standardized title for display. If only one
        title is needed, transcribe the title from the source
        itself.
    display_label:
      default: Title
    index_documentation: displayable, searchable
    indexing:
    - 'title_sim'
    - 'title_tesim'
    form:
      required: true
      primary: true
      multi_value: true
    mappings:
      metatags: twitter:title, og:title
      mods_oai_pmh: mods:titleInfo/mods:title
      qualified_dc_pmh: dcterms:title
      simple_dc_pmh: dc:title
    property_uri: http://purl.org/dc/terms/title
    range: http://www.w3.org/2001/XMLSchema#string
    requirement: required
    sample_values:
    - Pencil drawn portrait study of woman
  date_modified:
    available_on:
      class:
      - Hyrax::AdministrativeSet
      - Hyrax::FileSet
      - Hyrax::PcdmCollection
      - Hyrax::Work
    cardinality:
      minimum: 0
      maximum: 1
    multi_value: false
    display_label:
      default: Date Modified
    property_uri: http://purl.org/dc/terms/modified
    range: http://www.w3.org/2001/XMLSchema#dateTime
    sample_values:
    - "2024-06-06 21:06:51 +0000"
  date_uploaded:
    available_on:
      class:
      - Hyrax::AdministrativeSet
      - Hyrax::FileSet
      - Hyrax::PcdmCollection
      - Hyrax::Work
    cardinality:
      minimum: 0
      maximum: 1
    multi_value: false
    display_label:
      default: Date Uploaded
    property_uri: http://purl.org/dc/terms/dateSubmitted
    range: http://www.w3.org/2001/XMLSchema#dateTime
    sample_values:
    - "2024-06-06 21:06:51 +0000"
  depositor:
    available_on:
      class:
      - Hyrax::AdministrativeSet
      - Hyrax::FileSet
      - Hyrax::PcdmCollection
      - Hyrax::Work
    cardinality:
      minimum: 0
      maximum: 1
    multi_value: false
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Depositor
    index_documentation: searchable
    indexing:
    - 'depositor_tesim'
    property_uri: http://id.loc.gov/vocabulary/relators/dpt
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Julie Allinson
  creator:
    available_on:
      class:
      - Hyrax::FileSet
    cardinality:
      minimum: 1
    multi_value: true
    controlled_values:
      format: http://www.w3.org/2001/XMLSchema#string
      sources:
      - 'null'
    display_label:
      default: Creator
    index_documentation: searchable
    indexing:
    - 'creator_tesim'
    property_uri: http://purl.org/dc/elements/1.1/creator
    range: http://www.w3.org/2001/XMLSchema#string
    sample_values:
    - Julie Allinson
