apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fcrepo.fullname" . }}
  labels:
    {{- include "fcrepo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fcrepo.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "fcrepo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      serviceAccountName: {{ include "fcrepo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "fcrepo.fullname" . }}
      initContainers:
        - name: "remove-lost-found"
          image: "busybox:1.32.0"
          command:
            - rm
            - -fr
            - /data/lost+found
          volumeMounts:
            - name: data
              mountPath: /data
        {{- if not .Values.postgresql.enabled }}
        {{- if .Values.fcrepoSecretName }}
        - name: "init-db"
          image: {{ .Values.postgresql.image.repository | default "bitnami/postgresql" }}:{{ .Values.postgresql.image.tag | default "latest" }}
          command:
            - sh
            - -c
            - >
              PGPASSWORD=$DATABASE_PASSWORD PGHOST=$DATABASE_HOST PGUSER=$DATABASE_USER; export PGPASSWORD PGHOST PGUSER;
              psql -tc "SELECT 1 FROM pg_database WHERE datname = '$DATABASE_NAME'" | grep -q 1 ||
              createdb -e -w $DATABASE_NAME
          envFrom:
            - configMapRef:
                name: {{ include "fcrepo.fullname" . }}-env
            - secretRef:
                name: {{ include .Values.fcrepoSecretName . }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "fcrepo.fullname" . }}-env
            {{- if .Values.postgresql.enabled }}
            - secretRef:
                name: {{ template "fcrepo.fullname" . }}
            {{- else }}
            {{- if .Values.fcrepoSecretName }}
            - secretRef:
                name: {{ include .Values.fcrepoSecretName . }}
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ default 15 .Values.healthCheck.initialDelay }}
          readinessProbe:
            httpGet:
              path: /fcrepo
              port: http
            initialDelaySeconds: {{ default 15 .Values.healthCheck.initialDelay }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
