development:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8983/solr
test: &TEST  
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8984/fedora
  solr:
    url: http://localhost:8984/solr
production:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@your.production.server:8080/fedora
  solr:
    url: http://your.production.server:8080/solr 
cucumber:
  <<: *TEST
