development:
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  user: fedoraAdmin
  password: fedoraAdmin
  validateChecksum: true
test: &TEST  
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora-test
  user: fedoraAdmin
  password: fedoraAdmin
  validateChecksum: true
production:
  url: http://fedoraAdmin:fedoraAdmin@your.production.server:8080/fedora
  user: fedoraAdmin
  password: fedoraAdmin
  validateChecksum: true
cucumber:
  <<: *TEST
