# Define additional properties for OM terms to communicate with Solrizer
#   (Solrizer's use of dynamic fields to turn OM terms into Solr fields)
#  example:  t.my_term(:index_as=>[:searchable, :displayable])
#    implies that the Solr document will have fields my_term_t and my_term_display
#    if there is a value for the OM term  :my_term  in an object.
id: id
default: searchable
searchable: 
  default: _t
  date: _dt
  string: _t
  text: _t
  symbol: _s
  integer: _i
  long: _l
  boolean: _b
  float: _f
  double: _d
displayable: _display
facetable: _facet
sortable: _sort
unstemmed_searchable: _unstem_search